# Generated by Django 3.2.8 on 2021-10-10 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('full_name', models.TextField(default='')),
                ('vehicle_number', models.TextField(default='')),
                ('designation', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
