# Generated by Django 3.2.8 on 2021-10-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_registrations_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='v_type',
            field=models.TextField(choices=[('car', 'CAR'), ('Motor Bike', 'Motor Bike'), ('pickup van', 'pickup van')], default=''),
        ),
    ]
