# Generated by Django 3.2.8 on 2021-10-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211010_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logbook',
        ),
    ]
