# Generated by Django 3.2.8 on 2021-10-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_entry_exit'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='department',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone_no',
            field=models.TextField(default=''),
        ),
    ]
