# Generated by Django 3.2.8 on 2021-10-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_inout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InOut',
            new_name='Log',
        ),
    ]
