# Generated by Django 3.2.8 on 2021-10-11 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_inout_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='entry',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='exit',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.registration'),
        ),
    ]
