# Generated by Django 3.2.8 on 2021-10-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20211011_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
