# Generated by Django 3.2.8 on 2021-10-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='department',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='designation',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='full_name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone_no',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='stuff_id',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='vehicle_number',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='vehicle_type',
            field=models.TextField(choices=[('car', 'Car'), ('Motor Bike', 'Motor Bike'), ('pickup van', 'Pickup Van')], max_length=100),
        ),
    ]
