# Generated by Django 3.2.8 on 2021-10-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20211011_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='vehicle_type',
            field=models.TextField(choices=[('Car', 'Car'), ('Motor Bike', 'Motor Bike'), ('Pickup Van', 'Pickup Van')], max_length=100),
        ),
    ]
