# Generated by Django 3.2.8 on 2021-10-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20211013_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('In', 'In'), ('Out', 'Out')], default='In', max_length=100),
        ),
    ]
