# Generated by Django 3.2.8 on 2021-10-19 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_registration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('u_vehicle_number', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
