# Generated by Django 3.2.9 on 2021-11-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20211111_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='ts_created',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='ts_updated',
            field=models.TimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='exit',
            name='ts_created',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exit',
            name='ts_updated',
            field=models.TimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='ts_created',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='ts_updated',
            field=models.TimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='ts_created',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='ts_updated',
            field=models.TimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ts_created',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ts_updated',
            field=models.TimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='unregisteredvehicle',
            name='ts_created',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='unregisteredvehicle',
            name='ts_updated',
            field=models.TimeField(auto_now=True, db_index=True),
        ),
    ]
