# Generated by Django 3.2.9 on 2021-11-15 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_historyunregistered_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyunregistered',
            options={'verbose_name_plural': 'HistoryUnregistered'},
        ),
    ]
