# Generated by Django 3.2.9 on 2021-11-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_history_platenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='platenumber',
            field=models.CharField(max_length=100),
        ),
    ]
