# Generated by Django 3.2.9 on 2021-11-15 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_history_platenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='platenumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registration'),
        ),
    ]
