# Generated by Django 3.2.9 on 2021-11-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_history_platenumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historyunregistered',
            options={'verbose_name': 'HistoryUnregistered'},
        ),
        migrations.AlterField(
            model_name='history',
            name='platenumber',
            field=models.CharField(max_length=100),
        ),
    ]
