# Generated by Django 3.2.9 on 2021-11-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20211116_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(choices=[('In', 'In'), ('Out', 'Out')], default='In', max_length=100),
        ),
    ]
