# Generated by Django 3.2.9 on 2021-11-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_history_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='status',
        ),
    ]
